import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'SEO App',
    template: '%s | SEO App',
  },
  description: 'Generated by create next app',
  metadataBase: new URL('https://seo-ten-sand.vercel.app/'),
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://seo-ten-sand.vercel.app',
    title: 'SEO App',
    siteName: 'SEO App',
    description: 'Generated by create next app',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
